version: '3.9'

services:
  auth-service-redis:
    image: redis:latest
    container_name: auth-service-redis
    ports:
      - "6379:6379"

  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "8080:8080"
    depends_on:
      - auth-service-redis
    environment:
      - APP_ENV=${APP_ENV}
      - REDIS_ADDR=auth-service-redis:6379
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - SPOTIFY_REDIRECT_URL=${SPOTIFY_REDIRECT_URL}
      - ALLOWED_REDIRECT_DOMAINS=${ALLOWED_REDIRECT_DOMAINS}