services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=ci
    volumes:
      - ./env.ci:/app/.env.ci
    depends_on:
      - redis
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
