name: Docker Compose CI

on:
  push:
    branches:
      - master

jobs:

  # Step 1: Run Tests
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        run: go test ./... -v

  # Step 2: Build and Deploy (runs only if tests pass)
  build-and-deploy:
    runs-on: self-hosted

    needs: run-tests

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: |
          docker-compose down || true  # Stop existing containers
          docker-compose up --build -d  # Build and start containers

      - name: Set APP_ENV to dev
        run: echo "APP_ENV=dev"

      - name: Health Check
        run: |
          curl --fail http://localhost:8080/swagger/ || exit 1