name: Docker Compose CI

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: self-hosted # Use your mini PC runner

    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v4

      # Step 2: Set up Docker Compose
      - name: Set up Docker Compose
        run: |
          docker-compose down || true # Stop any existing containers
          docker-compose up --build -d # Build and start containers in detached mode

      # Step 3: Set APP_ENV to dev for now
      - name: Set APP_ENV to dev
        run: echo "APP_ENV=dev" >> $GITHUB_ENV

      # Step 4: Verify the service is running
      - name: Health Check
        run: |
          curl --fail http://localhost:8080/swagger/ || exit 1
